### ISSUE TITLE
No std? 

### ISSUE THREAD

**Issue by Restioson** [AdamNiederer/faster#11]
Hi! 

This crate looks great, and I was wondering whether it could have a use_std feature (on by default) so that it could be used in no_std environments. Coresimd, which looks like the core counterpart to stdsimd, could be perhaps  used?

**Comment by AdamNiederer** [comment]
Hello,

Have you tried compiling with the `no-std` feature enabled? That should strip any dependencies on `std`.

**Comment by Restioson** [comment]
... Wow, that wasn't smart of me. I must've missed that in the Cargo.toml. 🤦‍♂️ Thanks!

**Comment by Restioson** [comment]
Ah, it looks like I checked the repo out before you added it in, I think.
