### ISSUE TITLE
Renaming structs and traits

### ISSUE THREAD

**Issue by ralfbiedert** [AdamNiederer/faster#18]
I saw you renamed a lot of structs and traits. 

Since you are on this, I was wondering what you think about renaming `Packed` to `SIMDVector`, along with friends (e.g., `Packable` -> `SIMDConvertable`), or something similar.

Main reason is, when I started reading the source and tried to understand how all the `Pack*` concepts relate, I found your comment `Packed // A SIMD vector of some type` most helpful and thought _If that's what it really is, why isn't it just named liked that?_

I'm not proposing exactly these names, but think the crate's internals would be easier to follow if the names reflected "well known" concepts.

**Comment by AdamNiederer** [comment]
Intel refers to its vectors as "packed" types, whereas the RISC architectures usually call them "vectors". Given how overloaded "vector" is in computing, I'd rather avoid that if at all possible.

I will be updating a few more terms, like changing "Stripe" to "Stride" in reference to the strided load pattern used by these functions.

**Comment by ralfbiedert** [comment]
Fair enough. Thanks for explaining!
