### ISSUE TITLE
Support for Complex Numbers

### ISSUE THREAD

**Issue by razorheadfx** [AdamNiederer/faster#27]
First of all thanks for making this library, the API looks really neat.
I'm currently working on a project where I need to crunch a lot of complex numbers (esp. [Complex<f32>](http://rust-num.github.io/num/num_complex/type.Complex32.html)) and would love to use faster instead of hooking into external C libraries like [VOLK](http://libvolk.org).
Is support for complex types on your roadmap?

**Comment by AdamNiederer** [comment]
It looks like you could just transmute an `&[Complex32]` to an `&[f32]` and process it with a strided iterator, because the struct is `repr(C)`. Are there any things you are unable to do with that approach?

**Comment by razorheadfx** [comment]
Thanks, I'll give it a shot!
