### ISSUE TITLE
Package still active?

### ISSUE THREAD

**Issue by cvanelteren** [AdamNiederer/faster#64]
This crate is listed by the official docs for simd operations yet the current version 0.50 gives tons of compile errors, i.e. unfound symbols. Is this crate still active?

**Comment by AdamNiederer** [comment]
Hey there!

Sorry, haven't had much time to work on this crate as of late, but I do intend to get back to it - unfortunately, the best hardware I have at the moment can't do AVX2, so I've been prioritizing other things until I have something that can doesn't have to wait on a CI build.

I just published 0.5.1, which should compile on the latest nightly. A quick benchmark run reveals that LLVM hasn't caught up too much in the last 2 years, so hopefully the crate will still be useful in the meantime!

**Comment by GabrielMajeri** [comment]
@AdamNiederer We could help with the AVX2 parts if you open issues describing what needs to be fixed/added :)

**Comment by cvanelteren** [comment]
Thanks for the reply. Unfortunately with the lastest rust, installing the package results in 
`error: specified package `faster v0.5.1` has no binaries`
- rustc 1.46.0

**Comment by AdamNiederer** [comment]
> Thanks for the reply. Unfortunately with the lastest rust, installing the package results in
> `error: specified package `faster v0.5.1` has no binaries`
> 
>     * rustc 1.46.0

Are you installing via `cargo install`? `faster` is a library, so it shouldn't have any command-line binaries. You can use `faster` by including it in the `Cargo.toml` of the project you wish to speed up.

**Comment by cvanelteren** [comment]
Ah thanks I am converting from C++ and testing the waters. Forgot to put faster back in `Cargo.toml`. Thanks ;-)!
