### ISSUE TITLE
Compatibility with Rayon

### ISSUE THREAD

**Issue by spease** [AdamNiederer/faster#7]
It wasn’t clear to me if faster can also work with rayon. I tried the simple example both with into_* and placing par_iter before and after simd_iter with no luck. So it looks to me like this isn’t a supported combination right now, but if it is, an example would be nice.

Thanks!

**Comment by AdamNiederer** [comment]
You should be able to do something like

``` rust
vec.par_iter(|a| a.simd_iter().simd_map(|b| ...))
```

Faster is a library containing operations that can only be executed on a single thread, so it should be perfectly compatible with Rayon.

The above code won't compile on 0.2.1 because the API is unstable, but that should be the gist of it.

**Comment by spease** [comment]
So I'd need to be using master? Any general idea of when you're planning on making an official version that is compatible?

**Comment by AdamNiederer** [comment]
0.3.0 is coming out at the end of December, and it breaks more than half the API. You can use 0.2.1 with Rayon as well - I think it's just `.into_simd_iter().map(|a| {..})` instead. Just do whatever SIMD operations you want in your per-core closure.

**Comment by AdamNiederer** [comment]
0.3.0 has been released, and you should be able to use this with Rayon without much issue. If you have any further questions, feel free to re-open or file another issue.
