### ISSUE TITLE
Hi, I'm from 2022. Please fix the build.

### ISSUE THREAD

**Issue by uselessgoddess** [AdamNiederer/faster#71]
Or I will do it myself :(

**Comment by StHagel** [comment]
Hi, I'm from 2023. Did anyone fix it yet?

**Comment by uselessgoddess** [comment]
For now, I don't see the point in doing this as a lot of preventive maintenance will have to be done. It would probably fit well in `std::simd`, but right now I'm completely satisfied with `std::simd`.
