### ISSUE TITLE
From std::iter::Iterator to PackedIterator

### ISSUE THREAD

**Issue by polyfloyd** [AdamNiederer/faster#8]
Hi! 

I think that it would be great to be able to call `into_simd_iter()` on regular Iterators, e.g.:
```
iter::repeat(42.0)
    .into_simd_iter()
    // ...
```

This allows SIMD to be applied when buffering the data into a vector would be inefficient and provides better interop with std.

**Comment by AdamNiederer** [comment]
This sounds like a good idea! We won't be able to take advantage of vectorized loads, but we might be able to optimize that further once specialization lands.

**Comment by bugabinga** [comment]
Would this also apply to ranges? Those do not implement Iterator.

**Comment by AdamNiederer** [comment]
Hi all,

Unfortunately, I'm going to delay this to 0.5.0, where I plan to overhaul the iterator system and remove most (if not all) of the overhead associated with the current system. This is the highest priority item in 0.5.0, however, so it should be the next "big thing" to land.

> Would this also apply to ranges? Those do not implement Iterator.

That should be possible. We can probably vectorize it as well.
