### ISSUE TITLE
Change `simd_map(Fn)` to `simd_map(FnMut)`?

### ISSUE THREAD

**Issue by ralfbiedert** [AdamNiederer/faster#9]
When trying to work with the 0.3 `PackedIterator` I noticed `simd_map` and `simd_reduce` take a `Fn`. 

Would it make sense to relax this requirement to `FnMut`, so that the closures could modify their environment? 

Rust's [std::iter::Iterator](https://doc.rust-lang.org/std/iter/trait.Iterator.html) seems to mostly use `FnMut`, and for my current use case (iterating a 2nd `simd_iter` while iterating another one) I would like to cause "side effects". 

I assume my actual problem will be addressed in 0.4, but I could imagine people might have other reasons they could need this.

**Comment by AdamNiederer** [comment]
Resolved by #10.
